export const Products = [
  { product: "Shampoo", price: 2, unit: "€" },
  { product: "Bagnoschiuma", price: 2, unit: "€" },
  { product: "Assorbenti", price: 4, unit: "€" },
  { product: "Capsule lavatrice", price: 4, unit: "€" },
  { product: "Spazzolino", price: 1.5, unit: "€" },
  { product: "Legumi", price: 1, unit: "€" },
  { product: "Dentifricio", price: 1.5, unit: "€" },
  { product: "Detergente intimo", price: 2, unit: "€" },
  { product: "Detergenti pavimenti", price: 2, unit: "€" },
  { product: "Panna", price: 1.5, unit: "€" },
  { product: "Caffè", price: 1.5, unit: "€" },
  { product: "Crostatine", price: 2.5, unit: "€" },
  { product: "Zucchero", price: 0.8, unit: "€" },
  { product: "Affettati", price: 4, unit: "€/hg" },
  { product: "Pasta (specificare)", price: 0.9, unit: "€/kg" },
  { product: "Carne macinata", price: 5, unit: "€/kg" },
  { product: "Olio", price: 7, unit: "€/l" },
  { product: "Cipolla/aglio", price: 0.2, unit: "€" },
  { product: "Carote", price: 1, unit: "€/kg" },
  { product: "Insalata", price: 1, unit: "€/kg" },
  { product: "Prezzemolo", price: 1, unit: "€/kg" },
  { product: "Farina", price: 1, unit: "€/kg" },
  { product: "Sale", price: 1, unit: "€/kg" },
  { product: "Burro", price: 3, unit: "€/500gr" },
  { product: "Succo", price: 2, unit: "€" },
  { product: "Biscotti", price: 1.2, unit: "€" },
  { product: "Cereali", price: 1.5, unit: "€" },
  { product: "Lametta", price: 1.5, unit: "€" },
  { product: "Carta igienica", price: 1, unit: "€/4 rotoli" },
  { product: "Scottex", price: 5, unit: "€" },
  { product: "Petto di pollo", price: 8, unit: "€/kg" },
  { product: "Ravioli", price: 15, unit: "€/kg" },
  { product: "Pancarrè", price: 1, unit: "€" },
  { product: "Parmigiano", price: 8, unit: "€/kg" },
  { product: "Patate", price: 0.20, unit: "€/cad." },
  { product: "Passata di pomodoro", price: 1.2, unit: "€" },
  { product: "Funghi", price: 3, unit: "€/kg" },
  { product: "Riso", price: 1.2, unit: "€/kg" },
  { product: "Prodotto lavastoviglie", price: 3.5, unit: "€" },
  { product: "Detergente pavimenti", price: 1.8, unit: "€" },
  { product: "Pezze cucina", price: 1, unit: "€" },
  { product: "Spugna", price: 1, unit: "€" },
];